# Generated by Django 5.1.4 on 2025-01-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=30)),
                ('release_year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('runtime', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
