# Generated by Django 5.1.4 on 2025-01-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='cast',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
