# Generated by Django 5.1.5 on 2025-01-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developTool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developtool',
            name='content',
            field=models.TextField(verbose_name='개발툴 설명'),
        ),
        migrations.AlterField(
            model_name='developtool',
            name='kind',
            field=models.CharField(max_length=100, verbose_name='종류'),
        ),
        migrations.AlterField(
            model_name='developtool',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
    ]
