# Generated by Django 5.1.4 on 2025-01-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developTool', '0002_alter_developtool_content_alter_developtool_kind_and_more'),
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='devtool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='developTool.developtool'),
        ),
    ]
