# Generated by Django 5.1.5 on 2025-01-15 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_alter_idea_devtool'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
